### ISSUE TITLE
Read pixel physical size from HuBMAP metadata

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/mibi-pipeline#1]
The HuBMAP MIBI metadata spec contains the physical size for pixels, in the fields
* `resolution_x_value`
* `resolution_x_unit`
and similar for dimension `y`.

Read these physical sizes from HuBMAP `*metadata.tsv` files, and embed this information in the appropriate OME-XML attributes when writing OME-TIFF output files.

**Comment by mruffalo** [comment]
The Salmon RNA-seq pipeline has functionality for (optionally) reading HuBMAP metadata files, as in https://github.com/hubmapconsortium/salmon-rnaseq/blob/main/bin/salmon/salmon_wrapper.py#L43 and https://github.com/hubmapconsortium/salmon-rnaseq/blob/main/bin/salmon/salmon_wrapper.py#L66. The regex at https://github.com/hubmapconsortium/salmon-rnaseq/blob/main/bin/salmon/salmon_wrapper.py#L38 probably needs to be loosened a bit, likely to match something like `(.*)metadata.tsv$`.

**Comment by seschultz** [comment]
Updated collect_dataset_info.py, collect_output.py, and utils_ome.py to do this
